apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.github.tvbox.osc"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 100
        versionName "1.0.0-x86-jb"
        multiDexEnabled true

        ndk {
            abiFilters "x86"
        }
    }

    signingConfigs {
        release {
            storeFile file("TVBoxOSC.jks")
            storePassword "123456"
            keyAlias "tvbox"
            keyPassword "123456"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        pickFirst 'lib/x86/libijkplayer.so'
        pickFirst 'lib/x86/libijkffmpeg.so'
        pickFirst 'lib/x86/libijksdl.so'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation project(':player')

    // Android 4.2.2 必须的 MultiDex 支持
    implementation 'androidx.multidex:multidex:2.0.1'

    // UI 基础库兼容
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.android.material:material:1.2.1'

    // 网络与基础工具
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'org.greenrobot:eventbus:3.2.0'
    implementation 'com.squareup.okhttp3:okhttp:3.12.13' // 兼容低版本 Android TLS 协议
}
