apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.github.tvbox.osc"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 100
        versionName "1.0.0-x86-jb"
        multiDexEnabled true

        ndk {
            abiFilters "x86"
        }

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        pickFirst 'lib/x86/libijkplayer.so'
        pickFirst 'lib/x86/libijkffmpeg.so'
        pickFirst 'lib/x86/libijksdl.so'
        exclude 'META-INF/beans.xml'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation project(':player')
    implementation project(':quickjs')
    implementation project(':tvrecyclerview')

    // Android 4.2.2 启动必备分包支持
    implementation 'androidx.multidex:multidex:2.0.1'

    // AndroidX UI 基础套件
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.2.1'

    // Room 数据库组件
    implementation 'androidx.room:room-runtime:2.2.5'
    annotationProcessor 'androidx.room:room-compiler:2.2.5'

    // Glide 图片加载
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    // 网络与 DNS
    implementation 'com.squareup.okhttp3:okhttp:3.12.13'
    implementation 'com.squareup.okhttp3:okhttp-dnsoverhttps:3.12.13'
    implementation 'com.lzy.net:okgo:3.0.4'

    // 常用工具与服务
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'org.greenrobot:eventbus:3.2.0'
    implementation 'org.jsoup:jsoup:1.13.1'
    implementation 'com.google.zxing:core:3.4.1'
    implementation 'com.orhanobut:hawk:2.0.1'
    implementation 'com.kingja.loadsir:loadsir:1.3.8'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'commons-io:commons-io:2.8.0'
}
