plugins {
    id 'com.android.library'
}

android {
    compileSdkVersion 33

    buildFeatures {
        buildConfig false
    }

    defaultConfig {
        minSdkVersion 17    // 关键：从 19 降到 17，适配 Android 4.2.2
        targetSdkVersion 28

        ndk {
            abiFilters 'x86' // 关键：强制让库内原生 SO 编译或匹配 x86 架构
        }
    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api 'wang.harlon.quickjs:wrapper-android:2.1.0'
    api 'wang.harlon.quickjs:wrapper-java:2.1.0'
}
